name: "Update README.md"

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string

jobs:
  documentation:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/create-github-app-token@v1
        id: app-token
        with: 
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}          
          owner: ${{ github.repository_owner }}

      - name: 'Update README.md'
        shell: bash
        run: |
          set -x
          
          gh auth login --with-token
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "$(gh api /users/${GITHUB_ACTOR} | jq .name -r)"

          cat << EOF > ~/.netrc
          machine github.com
          login ${GITHUB_ACTOR}
          password ${GITHUB_TOKEN}

          machine api.github.com
          login ${GITHUB_ACTOR}
          password ${GITHUB_TOKEN}
          EOF

          chmod 600 ~/.netrc

          echo ${GITHUB_REPOSITORY}
          echo ${GITHUB_WORKSPACE}
          echo ${{ github.head_ref || github.ref_name }} 

          sed -i -e 's~{{module-name}}~'"${{ github.event.repository.name }}"'~g' ./README.md

          cat ./README.md

          git add ./README.md
          git commit -m "Update README."
          git push --set-upstream origin ${{ github.head_ref || github.ref_name }} 

        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SECRET_ID: ${{ secrets.ARM_SECRET_ID }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
          PAT: ${{ secrets.PAT }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        #  #GITHUB_PAT: ${{ secrets.PAT }}
