name: "GitVerson Workflow"

on:
  workflow_call:
    inputs:
      versionSpec:
        required: true
        type: string
        default: '5.12.x'
      configFilePath:
        required: false
        type: string
        default: './GitVersion.yml'
      dotNetVersion:
        required: false
        type: string
        default: '3.1.x'
      runs-on:
        required: false
        type: string
        default: 'ubuntu-latest'
      environment:
        required: false
        type: string
        default: ''

jobs:
  reusable-workflow:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Input version of GitVertion (workflow call)
        if: ${{ inputs.versionSpec }} != ''
        run: echo ${{ github.event.inputs.versionSpec }}

      - name: Input Gitversion configuration file path.
        if: ${{ github.event.inputs.username }} != ''
        run: echo ${{ github.event.inputs.GitVersionFilePath }}

      - name: Input DotNet install Version
        if: ${{ inputs.dotNetVersion }} != ''
        run: echo ${{ github.event.inputs.versionSpec }}

      - name: Input Agent
        if: ${{ github.event.inputs.username }} != ''
        run: echo ${{ github.event.inputs.runs-on }}

      - name: Input Environtemnt
        if: ${{ inputs.environment }} != ''
        run: echo ${{ github.event.inputs.versionSpec }}

      - uses: actions/checkout@v2.3.4 # Necessary to access local action
      
      #- name: Local Action Call Without Input
      #  id: local-action
      #  uses: ./.github/actions/release
      #  with:
      #    name: "World"
      #- name: Local Action Output
      #  run: echo "${{ steps.local-action.outputs.random }}"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install DotNet
        uses: actions/setup-dotnet@v1
      
      - name: Use actions/setup-gitversion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: ${{ github.event.inputs.versionSpec }}
      
      - name: Run GitVersion
        run: |-
          cd test-project
          GitVersion /updateassemblyinfo SharedAssemblyInfo.cs /ensureassemblyinfo
          if [ ! -f "SharedAssemblyInfo.cs" ]; then
            raise error "SharedAssemblyInfo.cs does not exist"
          fi

