name: "GitVerson Workflow"

on:
  workflow_call:
    inputs:
      versionSpec:
        required: false
        type: string
        default: '5.12.x'
      configFilePath:
        required: false
        type: string
        default: './GitVersion.yml'
      dotNetVersion:
        required: false
        type: string
        default: '3.1.x'
      runs-on:
        required: false
        type: string
        default: 'ubuntu-latest'
      environment:
        required: false
        type: string
        default: ''

jobs:
  release:
    runs-on: ${{ inputs.runs-on }}
    steps:
      #- uses: actions/checkout@v2.3.4 # Necessary to access local action

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install DotNet
        uses: actions/setup-dotnet@v1
      
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: ${{ inputs.versionSpec }}
          includePrerelease: false
          ignoreFailedSources: false
          preferLatestVersion: true

      - name: Bump Version
        id: version
        uses: gittools/actions/gitversion/execute@v1.1.1

      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 

      - name: Commit CHANGELOG
        run: |-
          set -x
          echo ${{ github.actor }}
          echo $GITHUB_WORKSPACE
          ls -l $GITHUB_WORKSPACE
          cat $GITHUB_WORKSPACE/CHANGELOG.md
          git config --global user.name 'Leandro Moreira'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}
          git add $GITHUB_WORKSPACE/CHANGELOG.md
          git commit -m "Update CHANGELOG."
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.SemVer }}
          release_name: Release ${{ steps.version.outputs.SemVer }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false