name: "SonarQube"

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: 'ubuntu-latest'
      sonar_version:
        required: false
        type: string
        default: 'master'
      organization:
        required: true
        type: string
      project_name:
        required: true
        type: string

jobs:
  release:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: terraform/
          args: >
              -Dsonar.organization=${{ inputs.organization }}
              -Dsonar.projectKey=${{ inputs.project_name }}