name: "Terraform Workflow"

on:
  workflow_call:
    workflow_dispatch:
      inputs:
        action:
          description: 'Action to execute for Terraform.'
          required: true
          type: choice
          default: 'plan'
          options:
            - plan
            - apply
            - destroy
        terraform_version:
          description: 'Version of Terraform.'
          required: false
          type: string
          default: '1.5.0'
        runs-on:
          description: 'Which S.O to execute Runner.'
          required: false
          type: string
          default: 'ubuntu-latest'
        environment:
          description: 'Select Environment'
          required: true
          type: string
          default: 'dev'
          options:
            - dev
            - staging
            - producion
      secrets:
        ARM_SUBSCRIPTION_ID:
          required: true
        ARM_TENANT_ID:
          required: true
        ARM_CLIENT_ID:
          required: true
        ARM_CLIENT_SECRET:
          required: true
        ARM_SECRET_ID:
          required: true


jobs:
  terraform:
    runs-on: ${{ github.event.inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ github.event.inputs.terraform_version }}

      #- name: Clone Repository
      #  shell: bash
      #  run: |
      #    git config --global user.name "${{ github.actor }}"
      #    git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      #    git clone https://github.com/leandromoreirati/built-library.git

      - name: 'Terraform ${{ github.event.inputs.action }}'
        shell: bash
        run: |
          set -x
          #git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          #git config --global user.name "$(gh api /users/${GITHUB_ACTOR} | jq .name -r)"
          #git config -l
          
          cat << EOF > ~/.netrc
          machine github.com
          login ${GITHUB_ACTOR}
          password ${GITHUB_TOKEN}

          machine api.github.com
          login ${GITHUB_ACTOR}
          password ${GITHUB_TOKEN}
          EOF

          chmod 600 ~/.netrc
          cat  ~/.netrc

          #git config --global url.https://github.com/.insteadOf git://github.com/
          #git remote add upstream "https://${GITHUB_TOKEN}@github.com/leandromoreirati/built-library.git"
          
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "git@github.com:"
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          #git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/built-library.git
          
          echo $GITHUB_ACTOR
          echo $GITHUB_TOKEN
          echo $GITHUB_REF
          echo $GITHUB_REF_NAME
          echo $GITHUB_REPOSITORY
          echo $ARM_SUBSCRIPTION_ID
          echo $ARM_TENANT_ID
          echo $ARM_CLIENT_ID
          echo $ARM_CLIENT_SECRET
          echo $ARM_SECRET_ID
          echo ${{ inputs.action }}
          echo ${{ secrets.ARM_SUBSCRIPTION_ID }}
          echo ${{ secrets.ARM_TENANT_ID }}
          echo ${{ secrets.ARM_CLIENT_ID }}
          echo ${{ secrets.ARM_CLIENT_SECRET }}
          echo ${{ secrets.ARM_SECRET_ID }}
          echo ${{ secrets.GITHUB_TOKEN }}
          
          ls -l .

          git clone https://github.com/leandromoreirati/built-library.git          

          bash build.sh ${{ github.event.inputs.action }}
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SECRET_ID: ${{ secrets.ARM_SECRET_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #  #GITHUB_PAT: ${{ secrets.PAT }}
