name: "workflow lab"

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      runs-on:
        required: false
        type: string
        default: 'ubuntu-latest'
      environment:
        required: false
        type: string
        default: ''
    secrets:
      PASSWORD:
        required: true

jobs:
  reusable-workflow:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setting Environment
        id: branch_check
        run: |
          echo "Running on branch ${{ github.base_ref }}"
          if [ "${{ github.base_ref }}" == "feature"]; then
            echo "::set-output name=environment::feature"
          elif [ "${{ github.base_ref }}" == "develop"]; then
            echo "::set-output name=environment::dev"
          elif [ "${{ github.base_ref }}" == "release"]; then
            echo "::set-output name=environment::hom"
          elif [ "${{ github.base_ref }}" == "main"]; then
            echo "::set-output name=environment::prod"
          else
            echo "Ambiente não encontrado"
          fi

      - name: Use Variable Setup in Previews Step
        run: |
          echo "I'm using variable ${{ steps.branch_check.outputs.env_name }}"
          echo  ${{ steps.branch_check.outputs.environment }}
          echo "${{ inputs.username }}"

    outputs:
      environment: ${{ steps.branch_check.outputs.environment }}

  deploy:
    runs-on: ${{ inputs.runs-on }}
    needs:
     - reusable-workflow
    environment: 
      name: ${{ needs.reusable-workflow.outputs.environment }}
    
    steps:
      - name: Environment
        run: |
          echo ${{ env.name }}