name: "workflow lab"

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      runs-on:
        required: false
        type: string
        default: 'ubuntu-latest'
      environment:
        required: false
        type: string
        default: ''
    secrets:
      PASSWORD:
        required: true

jobs:
  reusable-workflow:
    runs-on: ${{ inputs.runs-on }}
    outputs:
      environment: ${{ steps.branch_check.outputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setting Environment
        id: branch_check
        run: | 
          echo "Running on branch ${{ github.base_ref }}"
          if [[ "${{ github.base_ref }}" = "refs/heads/feature/workflow" ]]; then
            echo "::set-output name=environment::feature"
          elif [[ "${{ github.base_ref }}" = "refs/heads/develop" ]]; then
            echo "::set-output name=environment::dev"
          elif [[ "${{ github.base_ref }}" = ^refs/heads/release/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::set-output name=environment::hom"
          elif [[ "${{ github.base_ref }}" = "refs/heads/main" ]]; then
            echo "::set-output name=environment::prod"
          else
            echo "Ambiente não encontrado"
            exit 1
          fi

      - name: Use Variable Setup in Previews Step
        run: |
          echo "I'm using variable" ${{ steps.branch_check.outputs.environment }}
          echo  ${{ steps.branch_check.outputs.environment }}
          echo "${{ inputs.username }}"
          #echo "${{ env.environment }}"


  deploy:
    runs-on: ${{ inputs.runs-on }}
    needs:
     - reusable-workflow
    env: 
      environment: ${{ needs.reusable-workflow.outputs.environment }}
    
    steps:
      - name: Environment
        run: |
          echo ${{ needs.reusable-workflow.outputs.environment }}
          echo ${{ env.environment }}