name: "workflow lab"

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      runs-on:
        required: false
        type: string
        default: 'ubuntu-latest'
      environment:
        required: false
        type: string
        default: ''
    secrets:
      PASSWORD:
        required: true

jobs:
  reusable-workflow:
    runs-on: ${{ inputs.runs-on }}
    outputs:
      environment: ${{ steps.set_environment.outputs.environment }}
    steps:
      - name: Setting Environment
        id: set_environment
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master"]; then
            echo "::set-output name=environment::prod"
          elif [ "${{ github.ref }}" == "refs/heads/develop"]; then
            echo "::set-output name=environment::dev"
          elif [ "${{ github.ref }}" == "refs/heads/release"]; then
            echo "::set-output name=environment::hom"
          else
            echo "Ambiente não encontrado"
          fi
        
      - name: Use Variable Setup in Previews Step
        run: |
          echo "Estou rodando esse deploy no ambiente ${{ steps.set_environment.outputs.environment }}"
          echo ${{ env.environment }}
          echo "${{ inputs.username }}"

    